name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 24

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4


      - name: Test
        if: runner.os != 'Windows'
        run: chmod +x gradlew && ./gradlew test

      - name: Test (Windows)
        if: runner.os == 'Windows'
        run: ./gradlew test


      - name: Build
        run: ./gradlew build


      - name: Build CLI fat JAR
        run: ./gradlew :connect4-cli:shadowJar


      - name: Build UI jlink
        run: ./gradlew :connect4-ui:jlinkZip


      - name: Prepare release files (Linux)
        if: runner.os == 'Linux'
        run: |
          mkdir release

          cp core/build/libs/*.jar release/
          cp cli/build/libs/*all.jar release/
          cp ui/build/*.zip release/


      - name: Prepare release files (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          mkdir release

          Copy-Item core/build/libs/*.jar release/
          Copy-Item cli/build/libs/*all.jar release/
          Copy-Item ui/build/*.zip release/


      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-${{ matrix.os }}
          path: release/


  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: release


      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release/**/*.jar
            release/**/*.zip